// 1) [1, 4, 3]
// 2) It says that the console.log() call at line 4, character 15, that was called after the hello
///   method was called on line 13, character 1 (at the global level), is passed the argument "greeting", 
//    which is not defined. 
// 3) console.log(Math.sqrt(37))
// 4) 
// console.log(Math.max(1, 6, 3, 2));
// console.log(Math.max(-1, -6, -3, -2));
// console.log(Math.max(2, 2));

// 5) It returns a list of each word's length ("word" being the string split by one space between substrings)
//    in reverse order

// 6) 
// let allMatches = (words, regex) => {
//     let arr = []; 
//     words.forEach(word => word.match(regex)? arr.push(word): undefined);
//     return arr;
// }

// let words = [
//     'laboratory',
//     'experiment',
//     'flab',
//     'Pans Labyrinth',
//     'elaborate',
//     'polar bear',
// ];
  

// console.log(allMatches(words, /lab/));

// 7) Exception handling enables the program to handle expecific exceptions without terminating execution.
//    It uses try/catch. 

// 8)
// let isNotANumber = val => val !== val;

// 9)
// let isNegativeZero = num => 1 / num === -Infinity;

// 10) 
